version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: spring_practice
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root@123
    ports:
      - "3307:3306"
    volumes:
      - ./sql/queries.sql:/docker-entrypoint-initdb.d/queries.sql:ro
    networks:
      - mysql-network

volumes:
  mysql-data:

networks:
  mysql-network:
    driver: bridge
